version: '3'

services:
    jupyternotes:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        container_name: gusdatasci
        ports:
            - "8888:8888"
            - "81:80"
            - "8081:8080"
        environment:
            - AIRFLOW_HOME=/var/www/html/airflow
        volumes:
            - ./:/var/www/html

networks:
    gus-php-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "12.0.0.0/16"