version: '3'

services:
    jupyternotes:
        build: .
        container_name: gusdatasci
        ports:
            - "8888:8888"
        volumes:
            - ./:/work
        networks:
            gus-sci-network:
                ipv4_address: 12.0.0.2


networks:
    gus-sci-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "12.0.0.0/16"